# Generated by Django 3.1 on 2021-04-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_auto_20210418_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='boy',
            new_name='student',
        ),
    ]
